language: go
go:
  - 1.4
  - 1.5

services:
  - cassandra

before_script:
  # peg
  - go get -u github.com/pointlander/peg
  - go get github.com/peterh/liner
  - cqlsh -f schema/schema_test.cql

script:
  - ./build_verify.sh
  - go test -v ./...
